### ISSUE TITLE
How to disable semver without "v" prefix

### ISSUE THREAD

**Issue by ookangzheng** [nico2sh/semtag#23]
Is there any way to disable something like this, 
I hope something like `0.0.1-alpha.2`, without "v" prefix (`v0.0.1-alpha.2`)

```bash
semtag alpha -s patch
2021-01-25T03:31:53Z
v0.0.1-alpha.2
```

**Comment by nico2sh** [comment]
Not at the moment, it doesn't tag without the "v", although it still detects tags without it for bumping if you added that one manually.

**Comment by nico2sh** [comment]
Fixed here https://github.com/nico2sh/semtag/pull/6
